### ISSUE TITLE
Add support for downloading exposed TEKs only from local source (ie. non-EFGS TEKs)

### ISSUE THREAD

**Issue by pvieito** [RadarCOVID/radar-covid-backend-dp3t-server#7]
As expected, now that the EFGS integration has been completed with the [_one world_ approach](https://github.com/RadarCOVID/radar-covid-ios/issues/20#issuecomment-701033756), the Radar COVID backend publishes TEKs from both the EFGS and Radar COVID merged, thus making not viable to distinguish local and _foreign_ TEKs. Adding support for downloading local TEKs would allow the community and researchers to verify the system, [detect issues](https://github.com/RadarCOVID/radar-covid-backend-dp3t-server/issues/6) and [analyze its performance at the country and app level](https://github.com/pvieito/Radar-STATS) until public statistics are released ([like other countries already integrated on the EFGS do](https://www.immuni.italia.it/dashboard.html)).

**Comment by pantic79** [comment]
Hello,

filtering by country of origin functionality is currently WIP. Expected release date in mid December.

Thanks,

**Comment by pvieito** [comment]
Great to hear that, thanks! 👍🏻

**Comment by pvieito** [comment]
@pantic79 Hi! It seems that since the 2020-12-03 no EFGS TEKs are being published on the Radar COVID endpoint ([see the green plot on the Radar STATS summary graph](https://raw.githubusercontent.com/pvieito/Radar-STATS/master/Data/Resources/Current/RadarCOVID-Report-Summary-Plots.png)).

Is this related to the new support for filtering by origin country or a problem on the EFGS / Radar COVID backend EFGS ingestion?

**Comment by pantic79** [comment]
Hello @pvieito,

the second one. We found one TEK downloaded from efgs with a three character length country code. As far as we understand, this is an error and will be notfied to efgs team. 

Thanks.

**Comment by pvieito** [comment]
@pantic79 Interesting, thanks for the info!

**Comment by pvieito** [comment]
Hi! Any update on this? I have noticed the addition of the [`visitedCountries` parameter on the V2 endpoint](https://github.com/RadarCOVID/radar-covid-backend-dp3t-server/blob/develop/dpppt-backend-sdk/dpppt-backend-sdk-ws/src/main/java/org/dpppt/backend/sdk/ws/controller/GaenV2Controller.java#L174), but it seems to [be currently ignored](https://github.com/RadarCOVID/radar-covid-backend-dp3t-server/blob/5e2f28f6d95f28ed2757f6a799317f0d3fa3dbbd/dpppt-backend-sdk/dpppt-backend-sdk-data/src/main/java/org/dpppt/backend/sdk/data/gaen/JDBCGAENDataServiceImpl.java#L167).

**Comment by pantic79** [comment]
Hello,

yes!. As you see, we are planning to include filters for visited countries (and also country of origin) TEKs metadata. We had no time to test this functionality thoroughly before the latest release and we are willing to include it in the next backend release.

Thanks.

**Comment by pantic79** [comment]
Hello,

this is already present in the last published version (see originCountries parameter [here](https://github.com/RadarCOVID/radar-covid-backend-dp3t-server/blob/748c1ad8ee898cf2c436fa52f3a8c7f79dafaf68/dpppt-backend-sdk/dpppt-backend-sdk-ws/src/main/java/org/dpppt/backend/sdk/ws/controller/GaenV2Controller.java#L151)).

Thanks.

**Comment by pvieito** [comment]
@pantic79 That's great, thanks a lot!
