### ISSUE TITLE
Publish public statistics and open data

### ISSUE THREAD

**Issue by pvieito** [RadarCOVID/radar-covid-backend-dp3t-server#8]
The Radar COVID project should provide open data and public statistics for the community and researchers. Multiple other countries are already publishing these statistics as a way to add more transparency to the projects, allow researchers to analyze the performance of the Exposure Notification apps and more importantly, encourage app usage. The Radar COVID project should be one of them.

Metrics that should be published and updated daily:
- Number of shared diagnoses segmented by day, region (Spain's Autonomous Community), quality (ie. the number of TEKs shared) and if the diagnosis was shared with the EFGS or not.
- Number of downloads segmented by day, platform (Android vs. iOS) and platform version.
- Number of unique active apps (apps which are daily connecting to the Radar COVID server to download TEKs) by day, platform, platform version and app version.
- Number of alerts shown to high-risk users (only from verified devices) by day, platform, platform version and app version.

All this data should be available both for the general public in the official Radar COVID app/website and as open data in a public repository published as easily reusable files (CSV, JSON…).

Some examples from other countries:
- [Immuni Dashboard](https://www.immuni.italia.it/dashboard.html)
- [Immuni Open Data Repository](https://github.com/immuni-app/immuni-dashboard-data)
- [SwissCovid App Monitoring](https://www.experimental.bfs.admin.ch/expstat/en/home/innovative-methods/swisscovid-app-monitoring.html)
- COVID Tracking Ireland: [App Store](https://apps.apple.com/ie/app/covid-tracker-ireland/id1505596721), [Google Play](https://play.google.com/store/apps/details?id=com.covidtracker.hse&hl=en_US&gl=US)

**Comment by pantic79** [comment]
Hello,

currently, we are envisioning a dashboard module. We will consider your KPI suggestions to be incorporated.

Thanks.

**Comment by pvieito** [comment]
@pantic79 That's great! Please, keep us updated on that 😄

**Comment by pvieito** [comment]
Hi! One suggestion/request: could be possible for the `https://radarcovid.covid19.gob.es/kpi/statistics/basics` endpoint to expose not only the last result, but also all the previous published results? It seems that the apps already expect the response array to have multiple results and it would be great to easily plot the evolution without having to store each request.

**Comment by pantic79** [comment]
Hello,

your suggestion will be considered. Nevertheless, the current (approvation pending) design for statistics portal does not consider an evolution in time view for this KPI.

Thanks for your suggestion.

**Comment by pvieito** [comment]
Great [dashboard](https://radarcovid.gob.es/estadisticas/codigos-introducidos-a-casos-confirmados), congratulations and thank you!
