### ISSUE TITLE
Invalid response Content-Type for /v2/gaen/exposed

### ISSUE THREAD

**Issue by josemmo** [RadarCOVID/radar-covid-backend-dp3t-server#9]
There is a typo in the `GET /exposed` mapping for the v2 GAEN controller, Content-Type should be `application/zip` instead of `applicaton/zip`:

https://github.com/RadarCOVID/radar-covid-backend-dp3t-server/blob/5e2f28f6d95f28ed2757f6a799317f0d3fa3dbbd/dpppt-backend-sdk/dpppt-backend-sdk-ws/src/main/java/org/dpppt/backend/sdk/ws/controller/GaenV2Controller.java#L150-L157

It is a minor bug but it might break some clients.

**Comment by iCesofT** [comment]
Thanks @josemmo. We fixed it.
